version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yJcFOmQYjKeRbZEelinliKdbrPsRgwWS
      POSTGRES_DB: railway
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: gondola.proxy.rlwy.net
      DB_PORT: 14945
      DB_USER: postgres
      DB_PASSWORD: yJcFOmQYjKeRbZEelinliKdbrPsRgwWS
      DB_NAME: railway

volumes:
  pgdata:
